import React, { useState, useEffect } from 'react';
import ScientificInput from './ScientificInput';

const CellPotentials = () => {
  const [mode, setMode] = useState('calculate_emf');
  const [problem, setProblem] = useState(null);
  const [coeff, setCoeff] = useState('');
  const [exp, setExp] = useState('');
  const [feedback, setFeedback] = useState({ type: '', message: '' });

  const halfCells = [
    { eq: 'Mg²⁺(aq) + 2e⁻ ⇌ Mg(s)', e: -2.37 },
    { eq: 'Zn²⁺(aq) + 2e⁻ ⇌ Zn(s)', e: -0.76 },
    { eq: 'Fe²⁺(aq) + 2e⁻ ⇌ Fe(s)', e: -0.44 },
    { eq: 'Cu²⁺(aq) + 2e⁻ ⇌ Cu(s)', e: 0.34 },
    { eq: 'Ag⁺(aq) + e⁻ ⇌ Ag(s)', e: 0.80 },
    { eq: 'Cl₂(g) + 2e⁻ ⇌ 2Cl⁻(aq)', e: 1.36 }
  ];

  const generateProblem = (forcedMode = null) => {
    const modes = ['calculate_emf'];
    const selection = forcedMode || mode;
    const targetMode = selection === 'random' ? 'calculate_emf' : selection;

    setMode(targetMode);

    // Pick two distinctly separate half cells
    let idx1 = Math.floor(Math.random() * halfCells.length);
    let idx2 = Math.floor(Math.random() * halfCells.length);
    while (idx1 === idx2) { idx2 = Math.floor(Math.random() * halfCells.length); }

    const cellA = halfCells[idx1];
    const cellB = halfCells[idx2];

    const reductionCell = cellA.e > cellB.e ? cellA : cellB;
    const oxidationCell = cellA.e > cellB.e ? cellB : cellA;
    const cellEmf = reductionCell.e - oxidationCell.e;

    const questionText = `An electrochemical cell is assembled using standard laboratory conditions. One half-cell consists of the system [ ${cellA.eq} ] with E° = ${cellA.e > 0 ? `+${cellA.e}` : cellA.e} V. The other half-cell contains [ ${cellB.eq} ] with E° = ${cellB.e > 0 ? `+${cellB.e}` : cellB.e} V. Calculate the overall standard electromotive force (E°cell) generated by this combination.`;

    setProblem({ questionText, correctAnswer: cellEmf });
    setCoeff('');
    setExp('');
    setFeedback({ type: '', message: '' });
  };

  useEffect(() => {
    generateProblem('calculate_emf');
  }, []);

  const checkAnswer = () => {
    if (!coeff || isNaN(parseFloat(coeff))) return;

    const userVal = parseFloat(coeff) * Math.pow(10, exp === '' ? 0 : parseInt(exp));
    const error = Math.abs(userVal - problem.correctAnswer);

    if (error < 0.01) {
      setFeedback({
        type: 'success',
        message: `Correct! E°cell = +${problem.correctAnswer.toFixed(2)} V. The half-cell with the more positive potential always acts as the cathode (reduction site).`
      });
    } else {
      setFeedback({
        type: 'error',
        message: 'Incorrect. Use the formula: E°cell = E°(reduction site) - E°(oxidation site). The reduction system is always the half-cell with the more positive standard potential.'
      });
    }
  };

  if (!problem) return null;

  return (
    <div className="applet-container">
      <div className="w-full max-w-md mx-auto mb-6 px-4">
        <span className="block text-[10px] font-black uppercase tracking-widest text-slate-400 mb-1.5 text-center">
          Choose Practice Mode
        </span>
        <div className="flex items-center justify-center">
          <div className="w-full max-w-xs text-center bg-slate-100 py-2.5 rounded-xl text-xs font-black text-slate-600 border border-slate-200 shadow-sm">
            Standard Cell Potentials (E°cell)
          </div>
        </div>
      </div>

      <div className="applet-header">Standard Cell Potentials</div>
      <div className="question-text text-center px-2 leading-relaxed">{problem.questionText}</div>

      <div className="w-full flex items-center justify-center my-6 overflow-x-auto">
        <div className="flex flex-row items-center justify-center flex-nowrap whitespace-nowrap gap-1 px-4 py-2 bg-slate-50 border border-slate-200 rounded-2xl shadow-sm">
          <ScientificInput value={coeff} exponent={exp} onValueChange={setCoeff} onExponentChange={setExp} label="E°cell =" status={feedback.type} />
          <span className="text-sm font-bold text-slate-500 ml-1 select-none">V</span>
        </div>
      </div>

      <div className="button-group">
        <button className="btn btn-primary" onClick={checkAnswer}>Check Answer</button>
        <button className="btn btn-secondary" onClick={() => generateProblem()}>New Problem</button>
      </div>

      {feedback.message && <div className={`feedback-box ${feedback.type === 'success' ? 'feedback-success' : 'feedback-error'}`}>{feedback.message}</div>}
    </div>
  );
};

export default CellPotentials;
